tasks:
  - input: "配置文件名"
    output:
    - framework: "生成模块名"
      target: D:\codehouse\testcreate\apps\auto
    - framework: markfile
      target: D:\codehouse\testcreate\docs

model:
  name: "生成模块名"
  suppport:
  - markfile - "接口文档"
  - tornado - "tornado后端"
  - rpc - "rpc接口"
  - axios - "前端接口"
  - element-ui - "前端界面"
