tasks:
  - input: "配置文件名"
    output:
    - framework: "生成模块名"
      target: D:\codehouse\testcreate\api\auto
    - framework: markfile
      target: D:\codehouse\testcreate\docs

model:
  name: "生成模块名"
  suppport:
  - tornado - "tornado后端"
  - markfile - "接口文档"