tasks:
  - input: 
      配置模板文件名
    params:
      配置参数
      aio: 
        是否启用异步
    key:
      用于替换模板中的可替换部分， 一般是需要灵活扩展的内容
    output:
    - framework: 
        生成模块名
        markfile:
          接口文档
        tornado:
          tornado后端代码
        rpc:
          rpc接口代码
        element-ui:
          前端界面代码， 包含了axios部分代码
          通过yarn， yarn serve可以直接启动项目
        axios:
          前端接口代码
      target: 
        生成代码位置
